### ISSUE TITLE
求UI界面

### ISSUE THREAD

**Issue by konnyakuxzy** [eaglexiang/eagle.tunnel.go#1]
Linux不想用终端的制杖求Dalao能做出UI Orz。。。
大佬辛苦了，给大佬递茶QwQ

**Comment by eaglexiang** [comment]
UI在做，不过肯定无法马上提供 :) 
其实对于支持Systemd服务的Linux发行版来说，ET Go的使用还是挺方便的，基本使用的话你只需要配置 **一个** 参数就行。你只需到[最新发布](https://github.com/eaglexiang/eagle.tunnel.go/releases)下载对应的压缩包，解压后执行其中的安装脚本即可。
```shell
sudo ./install.sh
sudo systemctl enable eagle-tunnel-server
sudo systemctl start eagle-tunnel-server
```
而客户端方面才需要稍微配置一下服务器IP。
```shell
sudo ./install.sh
nano /etc/eagle-tunnel.d/client.conf # 你也可以使用其它任何你喜欢的文本编辑器
# 修改或添加relayer的值为服务器的IP
# relayer=x.x.x.x
sudo systemctl enable eagle-tunnel-client
sudo systemctl start eagle-tunnel-client
```

**Comment by konnyakuxzy** [comment]
蟹蟹大佬～
酸酸乳太久没更新容易被ban，试试比较小众的ET应该挺好QwQ

**Comment by konnyakuxzy** [comment]
大佬QAQ
我用electron实现了一个有UI界面的ET客户端
基本功能已经实现啦
（从今天早上开始从0学js。。。）
等下我就push到gayhub上
23333，不麻烦大佬啦OvO...

**Comment by eaglexiang** [comment]
@konnyakuxzy 吓，你真的太牛了:scream:

**Comment by konnyakuxzy** [comment]
@eaglexiang smg...Dalao不要fake...
我不过是写个壳而已QAQ...
实在是不想纠结了，什么v2ray也没有图形客户端啊酸酸乳啥的又凉了
现在还只实现了功能部分：
![](https://i.loli.net/2018/09/28/5bae11b725f39.png)

还有一些什么加到托盘后台运行，图标还没设计。。。也还没打包。。。也还没做windows的版本QAQ

害怕.jpg

感谢大佬做出et Orz，用了一天了感觉没断过还是很不错的（逃

话说et协议要怎么用呀？就是说。。。貌似什么浏览器的代理协议里也只有socks和http，没有et啊，怎么办QAQ

**Comment by eaglexiang** [comment]
哈哈，因为前端我真的太不在行了。
ET协议，简单地说就是服务端需要开启的协议。
ET其实没有严格的服务端客户端之分，如果三个协议同时打开，再把服务器IP填为本机IP，那他就是本机给本机代理了

**Comment by eaglexiang** [comment]
等你做好了放上来，说不定以后我都改用你的客户端了:smile:

**Comment by konnyakuxzy** [comment]
QAQ 那可真是荣幸之至23333
不过啊
当心到时候几吨BUG哦233333～
js是真的刚接触QwQ...
我赶紧写，尽量今天能写完（明天就有事情了。。。）

**Comment by konnyakuxzy** [comment]
已经发布啦QwQ...项目地址：[https://github.com/konnyakuxzy/et-electron](https://github.com/konnyakuxzy/et-electron)
因为真的是第一次写js还是有些奇怪的（比如windows版的那个目录下有好多好多.dll文件。。。可能electron就是这样的吧）
而且打包也没搞得很好，本来想打包成.deb和.appImage再传上来的但是好像没时间了
最近几天很忙.jpg QwQ
大佬请过目Orz

**Comment by eaglexiang** [comment]
简单使用了一下，非常牛:+1:不敢相信。比我之前鼓捣的高到哪里去了。等我再试用几天
