### ISSUE TITLE
许多未知的连接

### ISSUE THREAD

**Issue by gttwork** [eaglexiang/eagle.tunnel.go#10]
您好！感谢您开发这个软件，我在一台VPS上安装了以后一直没有连接，今天输入lsof -i后发现满屏都是不认识的连接，不知道为什么，我用了用户名和密码保护。
![tim 20190305212954](https://user-images.githubusercontent.com/16264455/53808908-6f7ed600-3f8e-11e9-9a5f-da73c1610d87.png)

**Comment by eaglexiang** [comment]
这可能是由网络上的嗅探流量引起，我每天也会收到大量陌生请求。一般情况这不会造成使用上的麻烦，v0.9会解决这个问题。

**Comment by gttwork** [comment]
感谢告知，等待新版。

**Comment by eaglexiang** [comment]
现在有一个未经过足够测试的版本[v0.9](https://github.com/eaglexiang/eagle.tunnel.go/releases/tag/v0.9)修复了您提到的Bug。

我会关掉这个issue，如果有其它问题，欢迎继续提issue。

**Comment by eaglexiang** [comment]
v0.9存在已知Bug，建议降级到v0.8.3或升级到v0.9.3（测试版）
