### ISSUE TITLE
firewall-cmd: command not found

### ISSUE THREAD

**Issue by pia** [eaglexiang/eagle.tunnel.go#11]
你好，在linux上按照https://github.com/eaglexiang/eagle.tunnel.go/blob/master/docs/guides/linux.md 安装服务端的时候报错：

root@vps:~/et/Eagle_Tunnel_Go# ./install.sh
get parameters...
done
installing libs
installing systemd units
installing config files
Failed to execute operation: Connection timed out
./scripts/after-install.sh: line 4: firewall-cmd: command not found
./scripts/after-install.sh: line 5: firewall-cmd: command not found

环境：ubuntu-16.04-x86_64

**Comment by eaglexiang** [comment]
首先请确定您的Ubuntu已更新，然后可以尝试重复执行安装脚本。如果仍然报错，可以手动执行以下指令（需要root权限）：

```shell
systemctl daemon-reload
```

关于以下两行日志属于正常现象可以忽略：

```shell
./scripts/after-install.sh: line 4: firewall-cmd: command not found
./scripts/after-install.sh: line 5: firewall-cmd: command not found
```

**Comment by eaglexiang** [comment]
可能我刚才没讲清楚，有问题的日志是以下这一行：

```shell
Failed to execute operation: Connection timed out
```

对应的执行命令为：

```shell
systemctl daemon-reload
```

它起到的作用是刷新systemd unit缓存，使你能够使用以下命令将ET设定为开机自启动的守护进程：

```shell
systemctl enable eagle-tunnel-server
systemctl start eagle-tunnel-server
```

如果手动操作也不行的话，你可能遭遇了systemd某个bug（已被新版本修复），参见：[github.com/systemd/systemd/issues/3353](https://github.com/systemd/systemd/issues/3353)

**Comment by remmina** [comment]
@pia 我记得我好像也遇到了这个问题，先执行一遍：`sudo apt install firewalld`
再运行安装脚本就行了吧

**Comment by pia** [comment]
@eaglexiang @remmina 感谢，已经用上了。用`sudo apt install firewalld`和 `systemctl daemon-reload`后还是出现timeout提示，但不影响使用哈哈。谢谢开发出这么好软件！！
