### ISSUE TITLE
服务端升级有点复杂

### ISSUE THREAD

**Issue by gttwork** [eaglexiang/eagle.tunnel.go#12]
目前升级服务端的方式有点复杂，特别是在多个VPS上操作时，建议参照V2ray的升级方式，复制粘贴一行代码即可完成升级，配置文件都不用改动。另外建立新连接时速度较慢。感谢开发这个优秀的软件，希望越来越强大。

**Comment by eaglexiang** [comment]
@gttwork 

### 配置文件

如果是以执行安装脚本`install.sh`的方式安装，ET的升级也是不需要改动配置文件的。如果需要，那一定是功能特性上作出了调整。

### 升级方式

如果您需要升级，基本流程为：

1. 下载新版本安装包
2. 解压
3. 执行`install.sh`
4. 重启服务

这个过程的确可以被封装成一键脚本，谢谢建议。

### 连接速度

如果您指的`智能模式`下的速度较慢，新的版本会作出一些改进。

如果您指的是`全局模式`下的速度较慢，这可能是由于ET没有复用TCP长连接。这主要出于安全上的考虑，可能是不容易解决的。

**Comment by gttwork** [comment]
我是按照您说的程序升级的，提示生成了new配置文件。
连接速度：我用的是本地pac，服务端用的是全局模式。

**Comment by eaglexiang** [comment]
@gttwork 新生成的应该是_new后缀的文件，这是正常的，属于模板文件的备份，不影响使用。如果是本地智能模式的话，会在新版有改善。

**Comment by gttwork** [comment]
原来如此，我还以为是要启用这个_new后缀的文件。

**Comment by eaglexiang** [comment]
@gttwork 这么说来的确存在误导性，你觉得如果把_new改为_backup会不会好些？或者压根就不在日志中提示了？

**Comment by gttwork** [comment]
我觉得改为_backup并且不用提示，我一看就知道是备份的了。

**Comment by eaglexiang** [comment]
新版已作出改进，您看看效果如何

**Comment by gttwork** [comment]
效果很好，方便易用，非常感谢。

**Comment by eaglexiang** [comment]
:wink: 那好我把这个issue关掉了，如果有状况欢迎再提
