### ISSUE TITLE
invalid reply

### ISSUE THREAD

**Issue by danielfx1220** [eaglexiang/eagle.tunnel.go#14]
The server returns "warning:invalid reply" when i use check command from my client server.
the server shows  that it's active(running)

**Comment by eaglexiang** [comment]
> The server returns "warning:invalid reply" when i use check command from my client server.
> the server shows that it's active(running)

@danielfx1220  Could you quote all log?

It's usually because of unhealthy net connection between your remote side and local side.

**Comment by danielfx1220** [comment]
用windows 命令行 和 et-electron 客户端都返回 invalid reply ,服务器端按说明配置 显示 running ，请问作者这是什么问题？感谢！

**Comment by danielfx1220** [comment]
vps是可以ping通 延迟200ms以内 端口也是正常的

**Comment by eaglexiang** [comment]
> 用windows 命令行 和 et-electron 客户端都返回 invalid reply ,服务器端按说明配置 显示 running ，请问作者这是什么问题？感谢！

如果你确实保证服务端和客户端的head参数一致、账户设置一致，一般是由于网络原因引起。

**Comment by danielfx1220** [comment]
head 参数值 用引号吗

**Comment by eaglexiang** [comment]
> vps是可以ping通 延迟200ms以内 端口也是正常的

请按照下面顺序排查：

1. 丢包率是否很高？
2. 按照[最小服务](https://github.com/eaglexiang/eagle.tunnel.go#%E7%AE%80%E6%98%93%E6%9C%8D%E5%8A%A1%E6%90%AD%E5%BB%BA)启动是否有问题？
3. 参数设置是否正确？

**Comment by eaglexiang** [comment]
> head 参数值 用引号吗

head参数值的引号也会被视作参数值的一部分。如果远端使用了引号，本地也必须使用。

**Comment by danielfx1220** [comment]
谢谢！我再排查一下.

**Comment by eaglexiang** [comment]
这个issue已经过去太长时间，我会关掉它。如果你仍然出现问题，请继续回复此issue或提出新的issue

**Comment by luckypoem** [comment]
@danielfx1220 
我也遇到一样的问题，你现在解决它了吗？
谢谢回复
