### ISSUE TITLE
IP被墙

### ISSUE THREAD

**Issue by gttwork** [eaglexiang/eagle.tunnel.go#17]
最近一个安装了eagle.tunnel.go的VPS IP被墙，不知道是否跟这个软件有关。

**Comment by eaglexiang** [comment]
@gttwork 我更愿意相信你被同IP段的隔壁波及。et的这么点用户，为它开发探测工具太不划算:sweat_smile:

**Comment by gttwork** [comment]
有道理，我就想知道别的用户有没有出现问题。我想有可能这个IP在我用之前上过黑名单。

**Comment by eaglexiang** [comment]
@gttwork 好，这个issue就留在这里吧，如果出现问题我们也方便第一时间意识到

**Comment by JasLin** [comment]
@eaglexiang @gttwork 用了几天，目前还能用：）

**Comment by eaglexiang** [comment]
快一个月了，请问有遇到新的情况吗？如果没有我就把这个issue关掉了

**Comment by gttwork** [comment]
被封IP已解禁，使用正常，没有新情况。谢谢！

**Comment by eaglexiang** [comment]
那就好
