### ISSUE TITLE
uninstall.sh 中 /scripts/after-uninstall.sh 不存在

### ISSUE THREAD

**Issue by Chlience** [eaglexiang/eagle.tunnel.go#2]
uninstall.sh 调用文件目录下/scripts/after-uninstall.sh 不存在，需要手动删除

**Comment by eaglexiang** [comment]
抱歉，这是打包失误。已在[v0.3](https://github.com/eaglexiang/eagle.tunnel.go/releases/tag/v0.3)的发布中进行修复。
PS：这个错误不会对程序有任何影响，它所做的是去掉Systemd服务对ET的缓存，而这在你重启电脑时也会自动完成。

**Comment by Chlience** [comment]
请问下能否整理一下教程并且增加日志功能，真的不知道怎么调啊...

**Comment by eaglexiang** [comment]
更新了一部分高级配置相关的教程。
查看日志可以通过systemd自带的指令：
```shell
sudo systemd status eagle-tunnel-client # 查看客户端日志
sudo systemd status eagle-tunnel-server # 查看服务端日志
```
不知道你具体遇到了什么问题，可以上issue继续提问: )
