### ISSUE TITLE
Windows 下无法连接

### ISSUE THREAD

**Issue by Chlience** [eaglexiang/eagle.tunnel.go#3]
服务端:Ubuntu 16.04lts
客户端:windows10

服务端配置：
listen=0.0.0.0
et=on

客户端配置
listen=0.0.0.0
relayer=（服务器ip）
http=on
socks=on

服务端开启命令：
systemctl start eagle-tunnel-server

客户端开启命令：
.\et.go.exe .\config\client.conf

状态截图：
服务端：
![image](https://user-images.githubusercontent.com/22586392/46216125-7b2bf800-c371-11e8-873b-15af40afb828.png)

客户端：

Proxy:
![qq 20180928230327](https://user-images.githubusercontent.com/22586392/46216681-bda20480-c372-11e8-8d36-d11379c462a1.png)

无法连接，尝试连接某 Linux 下成功连接的服务器失败，求问是不是 Win 客户端问题

**Comment by eaglexiang** [comment]
你好像使用的是SwitchyOmega插件，请将代理协议设置为HTTP或SOCKS5

**Comment by Chlience** [comment]
使用的 Socks5 同时尝试了 http，均无效

**Comment by eaglexiang** [comment]
看起来似乎是服务端的问题。我尝试用客户端执行ET自带的PING指令

```shell
et ask local ping
# 这是v0.3提供的功能
```

被告知连接失败。（你的截图暴露IP了）有可能是relayer IP填写错误，或者服务端防火墙未成功打开TCP 8080端口。

你可以用下述步骤尝试排查问题：

1. 将客户端的client.con暂时f配置为

```shell
relayer=127.0.0.1
listen=0.0.0.0
socks=on
http=on
et=on
```

运行ET后尝试打开百度。这可以判断ET客户端是否运行正常。

2. 将服务端的server.conf暂时配置为

```shell
relayer=127.0.0.1
listen=0.0.0.0
socks=on
http=on
et=on
```

运行ET后尝试使用curl打开Google

```shell
curl --socks5 127.0.0.1:8080 google.com
```

这可以判断ET服务端是否运行正常

**Comment by eaglexiang** [comment]
Windows的话应该执行

```shell
.\et.go.exe ask local ping
```

**Comment by Chlience** [comment]
其实我是打了码的qwq，等下删了....

**Comment by Chlience** [comment]
检测显示本地服务端没有问题，但是我的服务端报错
![image](https://user-images.githubusercontent.com/22586392/46220087-b7fcec80-c37b-11e8-9ae3-cf4ec89ef11a.png)
已经打开端口，但是服务仍然无法正常启用
![image](https://user-images.githubusercontent.com/22586392/46220123-cc40e980-c37b-11e8-843d-a0dd9868604a.png)

**Comment by eaglexiang** [comment]
请问ET和curl的日志分别是什么呢？如果方便的话麻烦发上来一下

**Comment by eaglexiang** [comment]
另外也可以尝试强制指定服务端的listen为外网IP（而不是0.0.0.0），因为不排除存在不同系统对0.0.0.0的兼容问题。

**Comment by Chlience** [comment]
![image](https://user-images.githubusercontent.com/22586392/46220511-e0d1b180-c37c-11e8-9533-f86a6851c990.png)

**Comment by Chlience** [comment]
![image](https://user-images.githubusercontent.com/22586392/46220593-2a220100-c37d-11e8-9b97-b4f8e9b58f3d.png)
强行修改监听后得到回复

**Comment by Chlience** [comment]
仍然无法使用
![qq 20180929002642](https://user-images.githubusercontent.com/22586392/46221013-73268500-c37e-11e8-9e9d-7b90c6dfd0d9.jpg)
![qq 20180929002521](https://user-images.githubusercontent.com/22586392/46221016-73bf1b80-c37e-11e8-8ad7-c6365a2b2321.jpg)

**Comment by Chlience** [comment]
现在有点怀疑是服务器问题，等下开台新的服务器试试

**Comment by Chlience** [comment]
新服务器上未开启防火墙，服务成功！

**Comment by eaglexiang** [comment]
哈哈，那就好。我刚才也实在是无法复现出你的状况，焦头烂额呢

**Comment by Chlience** [comment]
感谢！
猜想：在第一次配置时安装了两次，是否可能导致错误？
抑或是防火墙配置问题？
现recover 服务器，看是否重现问题

**Comment by eaglexiang** [comment]
不客气。具体的原因分析需要场景复现。不然的话就只有天知道了 :P

**Comment by Chlience** [comment]
emm 现在又出现了神奇的问题，开启user-check后连接不上...

**Comment by Chlience** [comment]
![image](https://user-images.githubusercontent.com/22586392/46238120-0f7c6780-c33e-11e8-8cdd-c6a856c20921.png)
![image](https://user-images.githubusercontent.com/22586392/46238132-1d31ed00-c33e-11e8-9a2f-8e4d9e302561.png)
![image](https://user-images.githubusercontent.com/22586392/46238148-3f2b6f80-c33e-11e8-87f1-4812d743b705.png)
![image](https://user-images.githubusercontent.com/22586392/46238187-7f8aed80-c33e-11e8-8990-5812ab539e24.png)
![image](https://user-images.githubusercontent.com/22586392/46238191-8285de00-c33e-11e8-8495-c727a26f2e7f.png)
![image](https://user-images.githubusercontent.com/22586392/46238183-7bf76680-c33e-11e8-82af-c2d8c9b19093.png)

**Comment by Chlience** [comment]
![image](https://user-images.githubusercontent.com/22586392/46238229-cd075a80-c33e-11e8-9f63-16036b129104.png)

**Comment by Chlience** [comment]
但是关闭user-check后可正常连接

**Comment by Chlience** [comment]
![image](https://user-images.githubusercontent.com/22586392/46238287-4dc65680-c33f-11e8-82e9-32af72952b32.png)
使用user后连接本地（127.0.0.1）失败

**Comment by eaglexiang** [comment]
这是一个Bug，谢谢你找到它

**Comment by eaglexiang** [comment]
已经在修订后的[v0.3](https://github.com/eaglexiang/eagle.tunnel.go/releases/tag/v0.3)中修复，可以按照[Linux用户 使用指南](https://github.com/eaglexiang/eagle.tunnel.go/blob/master/docs/guides/linux.md)重新覆盖安装服务端即可。
