### ISSUE TITLE
多终端同时连接只有一台能上网

### ISSUE THREAD

**Issue by konnyakuxzy** [eaglexiang/eagle.tunnel.go#4]
刚刚试了一下两台电脑（Ubuntu 18.04）同时开启et
出现：A能上网则B不能，B能上网则A不能
开启了用户验证，用的是相同用户（刚刚打错了）
请问这是。。。Bug吗QAQ
还是一个用户只能同时给一个终端使用？

**Comment by eaglexiang** [comment]
请问执行 et ask local auth，分别反馈什么呢

**Comment by eaglexiang** [comment]
Private账户只允许一个IP同时登陆，如果需要多IP共享账户，需要将账户设置为share类型。参考[用户认证](https://github.com/eaglexiang/eagle.tunnel.go/blob/master/docs/config.md#%E7%94%A8%E6%88%B7%E8%AE%A4%E8%AF%81)

**Comment by konnyakuxzy** [comment]
@eaglexiang Wow, nice job, it works!
之前确实是没有设置用户类型QwQ
是我没仔细23333
这个真是太棒了，配置比v2ray简单23333
像我这种智障就应该用et，蟹蟹大佬Orz
