### ISSUE TITLE
请问et有进行加密吗？

### ISSUE THREAD

**Issue by konnyakuxzy** [eaglexiang/eagle.tunnel.go#5]
QvQemmm想问作者大佬一个问题，et进行了加密吗？

如果加密了，是采用哪种加密的呢？

如果没加密，是否考虑添加加密呢？

（这其实是跟别人安利et的时候别人提出来的问题）

**Comment by eaglexiang** [comment]
有进行加密，但这种加密效果几乎可以忽略不计。它的作用是防止因为敏感关键字被嗅探，但如果别人真想针对进行破解，基本是没有难度的。
这么做的原因是因为按照公开统计，现在绝大部分的网站都已经启用HTTPS，其本身就是高度加密的，额外再套一层高度加密带来的的收益并不显著，却会带来较大的性能损失。

**Comment by eaglexiang** [comment]
目前，如果你被针对性监听，当你访问HTTPS站点时，有暴露风险的信息是［你访问了哪个网站］。
但你在这个网站看了什么，说了什么，做了什么。第三方是无法得知的。

**Comment by konnyakuxzy** [comment]
QwQ好的，知道了，谢谢～

**Comment by eaglexiang** [comment]
话说回来，如果你或你的朋友真的有匿名访问网络的需求，不如使用ET+Tor，这也是我自己的选择。

Tor是成熟的匿名通信方案，唯一的缺点就是在部分网络环境被屏蔽，而这正好可以靠ET的代理功能弥补 :P 

严格说来，目前网络上的各种代理工具都是不够安全的，少数能达到HTTPS级别的工具，其配置过程也是非专业者很难做完的。
