### ISSUE TITLE
考虑支持移动端吗

### ISSUE THREAD

**Issue by konnyakuxzy** [eaglexiang/eagle.tunnel.go#6]
emmmm我只是提个建议QwQ
因为我本身没有手机（逃
不过似乎移动端的支持很多人都需要QvQ
（比如我朋友）
大佬考虑一下呗

**Comment by eaglexiang** [comment]
移动端开发工作量比较大，需要等有大块时间的时候再实现。因为基本无法复用现有的代码。:grin:

**Comment by konnyakuxzy** [comment]
emmmm也没事QwQ反正我没有手机
大佬费心了23333
