### ISSUE TITLE
head如何设置为随机值?

### ISSUE THREAD

**Issue by frankpen** [eaglexiang/eagle.tunnel.go#7]
1.如何设置,保证服务端和客户端保证同步的随机值?
2.伪加密的情况下,会不会被轻易解算出真实的网站请求地址? 可以设定强制使用aes128吗?
3.head部分是加密的吗? 我一旦设置了head就无法连接成功(string是一致的,不用加""的吧),删除head值可以正常连接

**Comment by eaglexiang** [comment]
1. head的值，你可以随意自定义，只要不与其它通信协议的协议头冲突即可。
2. 会。AES128在正式分支里还未启用，以后会放进来。
3. head未加密（因为本来就是你自定义的值），如果加了引号，引号会被视作head内容的一部分。自定义head导致不成功，通常是由于与程序的其它模块发生冲突。可以检查head的值：
* 是否存在空格
* 是否存在制表符
* 是否与HTTP代理协议格式相似

**Comment by eaglexiang** [comment]
我这边测试显示：
配置1：无法工作
配置2：正常工作
不知道是否方便提供详细的配置文件？

**Comment by eaglexiang** [comment]
测试了你的配置文件，工作正常哦，要不然上[https://github.com/eaglexiang/eagle.tunnel.go/releases](https://github.com/eaglexiang/eagle.tunnel.go/releases)重新下载覆盖安装一下。
另外可能也需要注意一下防火墙是否开启。

**Comment by frankpen** [comment]
配置文件目录建议不要遍历查找了,就指定一个比如/etc/et什么的.面的多个配置文件共存,还不知道该删哪一个了.

**Comment by eaglexiang** [comment]
@frankpen 说得有道理

**Comment by frankpen** [comment]
建议启动就两种方式  1 命令行带参数 2 启动读取配置文件.
  最近两天做docker镜像,发现还是命令行参数启动的制作起来方便,好改动.
    等你改好了,我来做镜像试试,最近玩docker上瘾

**Comment by eaglexiang** [comment]
@frankpen [v0.7](https://github.com/eaglexiang/eagle.tunnel.go/releases/tag/v0.7)已经添加对参数化启动的支持，希望达到了你的预期。

我会关掉这个issue，如果有其它问题，欢迎新开issue。
