### ISSUE TITLE
user-check=off时无法正常工作

### ISSUE THREAD

**Issue by konnyakuxzy** [eaglexiang/eagle.tunnel.go#9]
et版本0.7.2
et服务端设置`user-check=off`，然后et客户端不设置用户时无法正常链接网络
用check命令返回no local user
不知道这个是bug吗？或者已经在新版中修复了？
\_(:зゝ∠)\_

**Comment by eaglexiang** [comment]
这是一个Bug，我会在今天稍后修复它 : )

**Comment by eaglexiang** [comment]
已经在[v0.8.3](https://github.com/eaglexiang/eagle.tunnel.go/releases/tag/v0.8.3)中修复这个问题 :D
